### ISSUE TITLE
[Bug] [Photon] Improve Photon OS cache update before installing package

### ISSUE THREAD

**Issue by keirazhang** [vmware/ansible-vsphere-gos-validation#97]
##### SUMMARY

When changes are made to Photon OS's repo, it requires to execute tdnf makecache to update its package cache. But when the repo is very large, it will take a very long time to update the cache. At present, we have two parameters for determining whether to update cache or not: tdnf_makecache and update_cache, which seems duplicate. 
```
    - block:
       - name: "Set the fact that tdnf has not made cache"
         set_fact:
           tdnf_makecache: False

       # When networking or dns is not ready, tdnf commands would fail
       # So here we add retries for tndf makecache
       - include_tasks: repo_update.yml
         vars:
           check_update_cmd: "tdnf makecache"

       - name: "Set the fact that tdnf has finished making cache"
         set_fact:
           tdnf_makecache: True
         when:
           - repo_update_output is defined
           - repo_update_output.stderr is defined
           - not repo_update_output.stderr
      when: >
        (tdnf_makecache is undefined) or
        (not tdnf_makecache) or
        (update_cache is defined and update_cache)
```

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below



```

##### CONFIGURATION

```paste below



```
